import type { Metadata } from "next";
import { iranSans, iranSansFaNum } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${iranSansFaNum.className}, ${iranSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
